version: "3.9"

services:

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - gateway
    restart: always

  gateway:
    build: ./gateway
    ports:
      - "8080:80"
    depends_on:
      - dealer-service
      - complaint-service
      - auth-service
    restart: always

  dealer-service:
    build: ./services/dealer-service
    restart: always
    depends_on:
      - db

  complaint-service:
    build: ./services/complaint-service
    restart: always
    depends_on:
      - db
    

  auth-service:
    build: ./services/auth-service
    restart: always

  db:
    image: mysql:8
    container_name: bpcl-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bpcl
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data:  