events {}

http {
    upstream dealer_service {
        server dealer-service:5000;
    }

    upstream complaint_service {
        server complaint-service:5001;
    }

    upstream auth_service {
        server auth-service:5002;
    }

    server {
        listen 80;

        location /api/dealers {
            proxy_pass http://dealer_service;
        }

        location /api/complaints {
            proxy_pass http://complaint_service;
        }

        location /api/auth {
            proxy_pass http://auth_service;
        }

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";
    }
}
