events {}

http {

    upstream complaint_service {
        server complaint-service:5000;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://complaint_service/;
        }
    }
}
